export const colors = {
  purplePlum: '#585CE5',
  violet: '#A1A3F6',
  peach: '#EEC1C1',
  sunnyYellow: '#F2D382',
  lilacPetals: '#FAFAFF',
  violetLight: '#D0D1FF',
  peachLight: '#F5DEDE',
  babyBlueLight: '#CFEBFF',
  white: '#FFFFFF',
  lightGray: '#E5E6EE',
  darkGrey: '#898D9E',
  turquoise: '#58C6CD',
  water: '#99D7DB',
  babyBlue: '#A6D0EE',
  alert: '#F59C9C',
  lilacPetalsDark: '#F0F1F9',
  waterLight: '#C9EBED',
  sunnyYellowLight: '#FBECC4',
  deepBlue: '#0F2851',
  coldGrey: '#415371',
  dustGrey: '#B0B2C3',
};
export const btnTextColor = {
  primary: colors.white,
  primaryInactive: colors.white,
  secondary: colors.purplePlum,
  secondaryInactive: colors.dustGrey,
};
